# Generated by Django 4.0.2 on 2022-09-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=30)),
                ('bookAuthor', models.CharField(blank=True, max_length=30, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
        ),
    ]
