# Generated by Django 4.0.2 on 2022-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookAuthor',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookName',
            field=models.CharField(max_length=128),
        ),
    ]
